services:
  - type: web
    name: speech-api
    env: python
    region: oregon
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        value: "10000"
